language: python
python:
    - 2.6
    - 2.7

install:
    - pip install -r src/crweb/requirements.txt
    - pip install -r src/crbridge/requirements.txt
    - pip install -r src/cram/requirements.txt

script:
    - python src/crweb/tests.py
